name: Auto Commit

on:
  schedule:
    - cron: "50 23 * * *" # run on 23:50 UTC
  workflow_dispatch:

jobs:
  check_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "wzw15292257101@163.com"
          git config --global user.name "dribble-njr"

      - name: Get all repositories
        run: |
          echo "Fetching all repositories..."
          response=$(curl -w "%{http_code}" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s "https://api.github.com/user/repos?type=all")

          http_code=$(echo $response | tail -n1)
          echo "HTTP status code: $http_code"

          contained_repos=$(echo $response | jq -r '.[] | .full_name')
          echo "Contained repositories: $contained_repos"

          echo "Fetched the following repositories:"
          cat repositories.txt

      - name: Read repositories list and check commits
        run: |
          date_today=$(TZ='Asia/Shanghai' date -I) # Date part
          time_start="${date_today}T00:00:00"
          time_end="${date_today}T23:55:00"
          commits_exist=false
          echo "Checking commits between $time_start and $time_end"

          while IFS= read -r repo; do
            echo "Checking commits for $repo"
            commit_today=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s "https://api.github.com/repos/$repo/commits?since=$time_start&until=$time_end")        
            if [[ -n "$commit_today" ]]; then
              echo "Commits today in $repo:"
              echo "$commit_today"
              commits_exist=true
              break
            fi

            if [[ "$commits_exist" == "false" ]]; then
              echo "No commits found today across all repositories. Creating a dummy commit..."
              echo "$(date) No commits found today" >> dummy.txt
              git add dummy.txt
              git commit -m "Auto commit on $(date)"
              git push
            else
              echo "Commits found today."
            fi

          done < repositories.txt
